### ISSUE TITLE
US1 - First elements and mobile optimization

### ISSUE THREAD

**Issue by chris-kuehn** [chris-kuehn/capstone-project#1]
## Value proposition

As a user interested in coding and design
I would like to see an introducing headline and the canvas of the mobile-only Art-Generator-App,
In order to get a first impression about the layout of the app.

## Description
![Bildschirm­foto 2023-08-14 um 12 48 54](https://github.com/chris-kuehn/capstone-project/assets/136816603/3e038512-3871-4d65-81ab-dee4ff1e0e55)

- Scribble / design or text
- Precise, no unnecessary information

## Acceptance criteria

- [ ] display the white surface of the mobile-only app on a grey background
- [ ] display the main headline "The Art Generator" wit a sans serif typeface
- [ ] display the canvas of the art generator with some padding and a black border

## Tasks

- [ ] create branch "first-elements-and-mobil-optimization"
- [ ] create h1 "The Art Generator", font-family: Helvetica/Arial/sans serif, font-weight: bold, font-size: 32px/2rem
- [ ] create a canvas element, height: 312px, width: 312px, border: 1px border-color: black
- [ ] create a div as a wrapper around the content with a width of 376 px and center it with using flexbox

**Comment by ninaassmann** [comment]
u don't need to specify the styling in the acceptance criteria
maybe the hard coded widths and height are not best practice, try using percentage or vw / vh
not every phone has the same size, so it can cause problems

**Comment by chris-kuehn** [comment]
Hi Nina, 

thank you so much for your super quick reply! :)

You are right, I will take the styling details out of the acceptance criteria.

Hard coded width and height are certainly not best practice!!! I will adjust the layout at a later time in a following user story and still work with fixed values in the current user story.

Thank you and happy coding!

Christian

**Comment by chris-kuehn** [comment]
Thank you Izabella for your feedback .... so lets do a bit of coding :)
