### ISSUE TITLE
On hold - US5 - Saving an artwork

### ISSUE THREAD

**Issue by chris-kuehn** [chris-kuehn/capstone-project#11]
## Value proposition

As a user
I want to save the current adjustment values of the art generator
in order to rebuild my artwork in the future (a following user story).

## Description
![Save-button](https://github.com/chris-kuehn/capstone-project/assets/136816603/57ac448a-a94d-4460-9826-62f8b3e83a68)

## Acceptance criteria

- [ ] After the save-button there is a adjustment button
- [ ] After pressing the button, the current adjustment values get saved in local storage

## Tasks

- [ ] declare a variable named "allArtworks" with an empty array 
- [ ] declare a function createParameterObject wich creates an object with all all current parameters of the art generator and an object ID
- [ ] declare a function UpdateLocalStorage wich saves the array "allArtwork" in local storage
- [ ] create a save button after the variation button
- [ ] add an onclick event to the button with a callback function wich will executes: createParameterObject(), add that object to the array, updateLocalStorage

**Comment by ninaassmann** [comment]
I would use a better name than UpdateLocalStorage
may updateAllArtWorks since you local storage state would look like this
const [allArtWorkds, setAllArtworks] = useLocalStorageState("artworks", {
    defaultValue: [],
  })
  
maybe  you could name this createParameterObject something like createArtwork

but those are just suggestions
