### ISSUE TITLE
US6 - Code Refactoring - Components

### ISSUE THREAD

**Issue by chris-kuehn** [chris-kuehn/capstone-project#12]
## Value proposition

As a web developer
I want to the code of this app easy to read and understand
In order to work on it or review it.

## Description

Check if the code is consistent and good structured. 
Check if it makes sense to divide existing components into smaller components

## Acceptance criteria

- [ ] The app should look like before refactoring
- [ ] The app should work like before refactoring

## Tasks

- [ ] Check variable names
- [ ] all color should define with hsla()
- [ ] components should not be to big

**Comment by JanaS87** [comment]
Sounds like a well planned refactoring 👍
