### ISSUE TITLE
US7 - separat inputs elements into a diffrent component

### ISSUE THREAD

**Issue by chris-kuehn** [chris-kuehn/capstone-project#14]
## Value proposition

As a developer
I want to use the canvas element as a single component
In order to use it in the studio and the gallery page.

## Description

- Scribble / design or text
- Precise, no unnecessary information

## Acceptance criteria

- [ ] The app should not show any changes

## Tasks

- [ ] create branch „create-components-canvas-inputs“

### Tasks on Canvas.js

- [ ] create a state variable with an array that summarizes all parameters of the canvas drawing in order to up lifiting
- [ ] create all necessary handle functions wich are used in the input elements in order to up lifiting
- [ ] implement the handle functions as call backs into the events of the inputs
- [ ] update the variables of the drawing statements
- [ ] test if all works correctly, if so commit

### Final Tasks
- [ ] up lifting of the state variable and the handle-functions
- [ ] separate the input elements into their own component
- [ ] using porps to send the state variable and the handle functions to canvas and input components
- [ ] test if all works correctly, if so commit

## Size L
