### ISSUE TITLE
US8 - creating a list of artworks on the gallery page

### ISSUE THREAD

**Issue by chris-kuehn** [chris-kuehn/capstone-project#17]
## Value proposition

As a u
I want to see different artworks on the gallerypage
In order to see how diffrent art works can look like.

## Description

![Scribble](https://github.com/chris-kuehn/capstone-project/assets/136816603/5d5a2add-0c48-40a5-a63e-afe2f3897bcb)

## Acceptance criteria

- [ ] You can see three diffreent artworks on the gallery page

## Tasks

- [ ] Create an state variable called listOfArtworks with an array
- [ ] the array contains three arrays with parameter of three different artworks
- [ ] Passing down the state variable listOfArtworks to the gallery page
- [ ] render a list of artworks by using the array methode map()
