### ISSUE TITLE
US2 – Minimal artwork and background-color-slider

### ISSUE THREAD

**Issue by chris-kuehn** [chris-kuehn/capstone-project#2]
## Value proposition

As a user interested in coding and design
I would like to see an artwork on the canvas and change the background color with a slider,
In order to adjust the background color.

## Description

![Bildschirm­foto 2023-08-14 um 16 04 06](https://github.com/chris-kuehn/capstone-project/assets/136816603/4c8e34ee-1a8c-43e8-9ea6-de38c24ad03e)

## Acceptance criteria

- [ ] The canvas has a background color
- [ ] The canvas shows a graphic element
- [ ] The background color can be adjusted with a slider, which is located below the canvas.

## Tasks

- [ ] branch "artwork-and-background-color-slider"
- [ ] connect the the HTML canvas element to the canvas api and set it content to 2D
- [ ] Define the background color and draw a graphic element with the methods of canvas
- [ ] place an Input element type slider
- [ ] Define a variable wich contains the hue value of the Background color (hsl)
- [ ] connect the slider output to that variable

**Comment by F-Kirchhoff** [comment]
you generally don't need to specify your user, in general, we only want to distinguish between different users only if you have different kind of users (b2c and b2b for example). So its enough for you to write `as a user` for all of your user stories.
Everything else looks good to me!
