### ISSUE TITLE
US9 - Add save button, display saved artworks on gallery page

### ISSUE THREAD

**Issue by chris-kuehn** [chris-kuehn/capstone-project#21]
## Value proposition

As a user
I want to save my artworks
in order to view them on the gallery page

## Description

![scribble](https://github.com/chris-kuehn/capstone-project/assets/136816603/1b1c6fa8-ce2b-432d-b976-99a65f5a50b1)

## Acceptance criteria

- [ ] you can finde a save button on the input section on the gallery page
- [ ] if you press the save button the is displayed on the gallery page

## Tasks

- [ ] create a listOfArtwork array to _app.js
- [ ] add save button with an onclick-event on input.js
- [ ] implement a callback function wich add the canvasParameter array to the list of Artworks array

**Comment by chris-kuehn** [comment]
Thank you! You are right there were two words missing ;) Happy weekend

**Comment by izabelladobielewska** [comment]
Happy weekend ☺️
