### ISSUE TITLE
US10 - Save listOfArtworks - array in local storage

### ISSUE THREAD

**Issue by chris-kuehn** [chris-kuehn/capstone-project#22]
## Value proposition

As a user
I would like to save my artwork permanently 
in order that they are not deleted after I close the app.

## Description

![scribble](https://github.com/chris-kuehn/capstone-project/assets/136816603/a5586f6a-1e1e-4a9a-9119-47f692a24830)

## Acceptance criteria

- [ ] Artwork in the gallery remains in the gallery after closing and reopening the app.

## Tasks

- [ ] install use-local-storage-state-library
- [ ] import use-local-storage-state-library to the _app.js document
- [ ] change the state variable list-of Artworks into use-local-storage-state

**Comment by bastianborndoerfer** [comment]
LGTM 👌
