### ISSUE TITLE
US11 - Code Refactoring - New data Structure

### ISSUE THREAD

**Issue by chris-kuehn** [chris-kuehn/capstone-project#24]
## Value proposition

As a developer
I want to work on an project with a clear data structure
In order to understand the code easily.
## Description

No Changes!

## Acceptance criteria

- [ ] The App should look and work like before

## Tasks

- [ ] Change structure of canvasParameter
- [ ] Adjust all functions and statements wich work with this parameter
