### ISSUE TITLE
US12 - Add a delete button

### ISSUE THREAD

**Issue by chris-kuehn** [chris-kuehn/capstone-project#26]
## Value proposition

As a user
I want to delete an artwork in my gallery 
in order to delete artworks i don't need anymore

## Description

![Scribble](https://github.com/chris-kuehn/capstone-project/assets/136816603/ceeb219a-2321-415f-b01f-e641165104a1)

## Acceptance criteria

- Under the artwork on the gallery page there is a delete button
- After pressing the button the artwork will be deleted

## Tasks

- [ ] Implement a way to create an ID that will work even after an artwork is deleted
- [ ] Add a delete button
- [ ] Implement a function that deletes a specific object from the array

**Comment by KilianBau** [comment]
You can use UID for creating an unique ID.
