### ISSUE TITLE
US13 - Adjusting Layout to diffrent mobile sizes and adding studio header animation

### ISSUE THREAD

**Issue by chris-kuehn** [chris-kuehn/capstone-project#28]
## Value proposition

As a user
I want to see an animation in the studio header section and the should look good on different mobile devices
In order to have a good first impression and good user expirience.

## Description

![Bildschirm­foto 2023-09-06 um 14 19 32](https://github.com/chris-kuehn/capstone-project/assets/136816603/160d5bd0-7abf-41cd-809b-035eb0590c97)

## Acceptance criteria

- [ ] In the header section you can see an animation in the background
- [ ] the H1 and the paragraph are in front of the animation
- [ ] the web-App and all its Elements should look fine on different mobile devices
- [ ] the navigation should covered by any any other element

## Tasks

- [ ] Change the widths dimension of the app from hard coded to flexible values
- [ ] resize the canvas element to fit different screen sizes  
- [ ] add a canvas element to the background of the studio header
- [ ] implement an animation in the canvas element

**Comment by milodevhh** [comment]
Hey Christian, I like, I wish you a lot of fun with this subsection.
