### ISSUE TITLE
US14 - Adding gallery header animation

### ISSUE THREAD

**Issue by chris-kuehn** [chris-kuehn/capstone-project#30]
## Value proposition

As a user
I want to see an animation in the studio header 
In order to have a good impression when i visit the gallery page.

## Description

<img width="259" alt="Bildschirm­foto 2023-09-08 um 14 05 54" src="https://github.com/chris-kuehn/capstone-project/assets/136816603/8f53ca02-6c09-440b-9779-1be694d83a27">

## Acceptance criteria

- [ ]  In the header section of the gallery page you can see an animation in the background
- [ ]  the H1 and the paragraph are in front of the animation

## Tasks

- [ ] add a canvas element to the background of the studio header
- [ ]  implement an animation in the canvas element
