### ISSUE TITLE
US15 - Add a download button

### ISSUE THREAD

**Issue by chris-kuehn** [chris-kuehn/capstone-project#31]
## Value proposition

As a user
I want to download an artwork
In order to post it on instagram

## Description

<img width="262" alt="Bildschirm­foto 2023-09-08 um 14 50 05" src="https://github.com/chris-kuehn/capstone-project/assets/136816603/468bd8a4-5045-4f9e-9101-08793f40eaf6">

## Acceptance criteria

- [ ] you can find a download button under each saved artwork on the gallery page
- [ ] if you press the button the related artwork gets downlod as a png picture 1080 x 1080px

## Tasks

- [ ] add a download button to the saved artworks
- [ ] use toDataURL() method to get a picture of the canvas

**Comment by NicoleHoerner** [comment]
Nice! Being able to download files/pictures is always great!
