### ISSUE TITLE
US16 - add another artwork generate

### ISSUE THREAD

**Issue by chris-kuehn** [chris-kuehn/capstone-project#32]
## Value proposition

As a user
I want to work with different art generators
In order to create different type of artworks

## Description

<img width="262" alt="Bildschirm­foto 2023-09-08 um 14 50 05" src="https://github.com/chris-kuehn/capstone-project/assets/136816603/6f6b81ab-c1f4-42ed-ad18-5e0fb386cc0a">

## Acceptance criteria

- [ ] You can find at least two art generators on the studio page

## Tasks

- [ ] add another canvas component 
- [ ] add add drawing statements
- [ ] add input elements component
