### ISSUE TITLE
US3 - Create archive page

### ISSUE THREAD

**Issue by chris-kuehn** [chris-kuehn/capstone-project#5]
## Value proposition

As a user who has already used the art generator
I would like to see an archive page where I can see the artwork I have already created,
in order to store all the artworks I have created in one place and view them again

## Description

- Scribble / design or text
- Precise, no unnecessary information

## Acceptance criteria

- [ ] a new page called archive is created
- [ ] On the new Page is a dummy-Artwork visible
- [ ] below the artwork is the date of creation

## Tasks

- [ ] creae branch "create-archive-Page"
- [ ] create a new static page
- [ ] add the CanvasOne component to the page
- [ ] add a paragraph with the date of creation

**Comment by CJAkkuec** [comment]
Re: VP
> As a user who has already used the art generator
> I would like to see an archive page where I can see the artwork I have already created,
> in order to store all the artworks I have created in one place and view them again

> As a user I want to be able to store the images I've created using the generator so that I can view them again.
Best to keep it concise. ;) 

Re: Acceptance Criteria
 > a new page called archive is created
 
Not an acceptance criteria, unless you want to express that the user can access it.

Re: Tasks
> creae

*create :D

 > add the CanvasOne component to the page
 
I'm not sure that's what you want to do. Shouldn't you want to be able to save the image you created rather than displaying the canvas again?

**Comment by CJAkkuec** [comment]
**Re: Acceptance Criteria**
> minimum two more input-elements to customize the art work

Please state a fixed number of inputs. Please also state what they do.

> the artwork should change by using the input-elements or by using a re-render-button

The "expected" behavior would be that the artwork changes with every increment the handler is moved in either direction - think: color pickers, etc. If you want the user to move the handlers and then submit a new artwork "request" based on the given specifications, then you need the button. You need to state what the behavior should be, otherwise the AC can't be met.

**Re: Tasks**
Your tasks are going to be quite different based on how you define the approach mentioned above.

 > create branch "multiple Input Elements"
 
 I'd prefer you name it something like feature/customization.

**Comment by chris-kuehn** [comment]
Thanks for your feedback. I have adjusted my user story.
