### ISSUE TITLE
US4 - Global Navigation

### ISSUE THREAD

**Issue by chris-kuehn** [chris-kuehn/capstone-project#6]
## Value proposition

As a user
I want to switch between the studio and the archive page
In order to navigate through the app

## Description

![Navigation](https://github.com/chris-kuehn/capstone-project/assets/136816603/c876e2ae-db2b-46fe-96a2-b2601ed9775b)

## Acceptance criteria

- [ ] A navigation at the top of the screen
- [ ] navigation is not influenced by scrolling
- [ ] navigation has a hover effect
- [ ] navigation shows which page you are on

## Tasks

- [ ] create a navigation component
- [ ] create the navigation nav-ul-li-link
- [ ] Style navigation: position fixed, hover-effect
