### ISSUE TITLE
US4 - Navigation and gallery page

### ISSUE THREAD

**Issue by chris-kuehn** [chris-kuehn/capstone-project#8]
## Value proposition

As a us
I want to uste a navigation to switch between the studio page and the gallery page
In order to create new artworks and watch existing artworks.

## Description
![Navigation and gallery page](https://github.com/chris-kuehn/capstone-project/assets/136816603/e62dfe4a-e615-4cd5-91c8-4077d956ae1f)

## Acceptance criteria

- [ ] You can find a navigation with two navigation points: Studio, Gallery?
- [ ] when you hover over a navigation point it changes its appearance. 
- [ ] The navigation is full functionally and you can switch between the studio and the gallery page.
- [ ] in order to switch to a gallery page there must be a gallery page. The gallery page shows a headline and an artwork. 

## Tasks

- [ ] Create a navigation with 2 navigation points: Studio, Gallery
- [ ] Create a gallery page

**Comment by StanislavOlijnik** [comment]
LGTM!
